# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0adb44e421ed8c25088bae12ac2dc5646cc30d9e60fd3ad28aa7fab3410ad349984485ffefc006d26c596ccb62eeefca5e4232980e06dd0898ac300f05766a1

test:
  secret_key_base: 5324e8fa78bce186e06b2de671924ec7580ec1e717270bfb3de8ed6482880b2cf78604362cd54173a0d3a17a36c2572691beeb8572aed322517698eeeeae3916

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
